name: build-on-command

on:
  workflow_dispatch:
# push:
#   paths:
#     - Dockerfile
#     - Makefile
#     - '.github/workflows/build-on-commit.yaml'

env:
  PLATFORMS: linux/arm/v7,linux/arm64,linux/amd64

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    -
      name: Do Checkout
      uses: actions/checkout@v4
    - 
      name: Allow `git`
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    -
      name: Install Grain
      run: |
        sudo curl -L --output /usr/local/bin/grain https://github.com/grain-lang/grain/releases/download/grain-v0.6.3/grain-linux-x64
        sudo chmod +x /usr/local/bin/grain
    -
      name: Install WABT
      run: sudo apt-get install -y wabt 
    -
      name: Build WASM files
      run: |
        make clean
        make
    -
      name: Commit WASM files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git status
        git pull
        git config advice.addIgnoredFile false
        git add plugin.wasm
        git commit -m 'update wasm from build'
        git push origin main
    - name: Save Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: "./*"